name: bookand
description: Bookand Mobile Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  intl: ^0.17.0
  firebase_core: ^2.1.1
  firebase_core_platform_interface: ^4.5.2
  firebase_crashlytics: ^3.0.4
  firebase_analytics: ^10.2.1
  firebase_performance: ^0.9.0+11
  flutter_riverpod: ^2.2.0
  riverpod_annotation: ^2.0.4
  flutter_svg: ^2.0.0+1
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  flutter_markdown: ^0.6.12
  chopper: ^6.1.0
  json_annotation: ^4.8.0
  sign_in_with_apple: ^4.1.0
  flutter_native_splash: ^2.2.12
  logger: ^1.1.0
  flutter_secure_storage: ^8.0.0
  go_router: ^6.0.6
  path_provider: ^2.0.11
  shake: ^2.2.0
  archive: ^3.3.6
  easy_debounce: ^2.0.3
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.5
  device_info_plus: ^8.2.1
  firebase_app_check: ^0.1.1+8
  package_info_plus: ^3.0.3
  image_picker: ^0.8.6+2
  cached_network_image: ^3.2.3
  http: ^0.13.5
  dropdown_button2: ^2.0.0
  collection: ^1.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  tuple: ^2.0.1
  stack_trace: ^1.11.0
  google_maps_flutter: ^2.2.5
  url_launcher: ^6.1.10
  maps_launcher: ^2.2.0
  share_plus: ^6.3.1
  firebase_remote_config: ^4.0.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^14.0.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  riverpod_generator: ^2.1.6
  chopper_generator: ^6.0.0
  hive_generator: ^2.0.0
  freezed: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/my/
    - assets/images/bookstore/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700
