name: bookand
description: Bookand Mobile Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  firebase_core: ^1.22.0
  firebase_crashlytics: ^2.8.10
  firebase_analytics: ^9.3.5
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  flutter_markdown: ^0.6.12
  dio: ^4.0.6
  get_it: ^7.2.0
  json_annotation: ^4.7.0
  sign_in_with_apple: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - bookand_app.env
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700