name: bookand
description: Bookand Mobile Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.3+5

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  intl: ^0.17.0
  firebase_core: ^2.1.1
  firebase_core_platform_interface: ^4.5.2
  firebase_crashlytics: ^3.0.4
  firebase_analytics: ^10.0.4
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  flutter_markdown: ^0.6.12
  dio: ^4.0.6
  json_annotation: ^4.7.0
  sign_in_with_apple: ^4.1.0
  flutter_native_splash: ^2.2.12
  logger: ^1.1.0
  flutter_secure_storage: ^6.0.0
  retrofit: ^3.3.1
  go_router: ^5.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  retrofit_generator: ^4.2.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700