// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvRu7KNG9oDHs7LlMd5FTONI5bazSYJU',
    appId: '1:336065052158:android:524822d5dd6ba808e314af',
    messagingSenderId: '336065052158',
    projectId: 'bookand-154bf',
    storageBucket: 'bookand-154bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW09mMxrVLNgRyrKh-iRZoABnGYghajSo',
    appId: '1:336065052158:ios:e5cf28fd4289861fe314af',
    messagingSenderId: '336065052158',
    projectId: 'bookand-154bf',
    storageBucket: 'bookand-154bf.appspot.com',
    androidClientId: '336065052158-dkqspd6bnqe8j3ronv43l31btgh72ngq.apps.googleusercontent.com',
    iosClientId: '336065052158-vdk4gu5qdi7nuof531iivd8dg34njpos.apps.googleusercontent.com',
    iosBundleId: 'kr.co.bookand.mobile',
  );
}
