// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0VRCMum_G301J3dW1tsbLsYLZcNIem40',
    appId: '1:936059076861:android:cf32d4907b0cb0addc7e94',
    messagingSenderId: '936059076861',
    projectId: 'bookand-dev',
    storageBucket: 'bookand-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbtMlUrvRBfubxPz6wtNSlGhHTznZ__Ps',
    appId: '1:936059076861:ios:84e80f825df60c9adc7e94',
    messagingSenderId: '936059076861',
    projectId: 'bookand-dev',
    storageBucket: 'bookand-dev.appspot.com',
    androidClientId: '936059076861-8cfdjdej3va6n6dhas5r5b92imb0of9n.apps.googleusercontent.com',
    iosClientId: '936059076861-bsvmuacduv8tf7c0oa01v9j7f3i7kehf.apps.googleusercontent.com',
    iosBundleId: 'kr.co.bookand.mobile.dev',
  );
}
